### ISSUE TITLE
Binding to V4-mapped V6 addresses?

### ISSUE THREAD

**Issue by martinduke** [martinduke/draft-tsvwg-udp-ecn#6]
UDP sockets behave pretty erratically when the application does this and tries to setsockopt(). Chrome is handling all this, but maybe this is too useless to go into in the draft?

**Comment by mxinden** [comment]
For what my opinion is worth, I believe documenting behavior of V4-mapped V6 is helpful. E.g. one datapoint where this has bitten me before is https://github.com/quinn-rs/quinn/pull/1765.

**Comment by tuexen** [comment]
> UDP sockets behave pretty erratically when the application does this and tries to setsockopt(). Chrome is handling all this, but maybe this is too useless to go into in the draft?

Do you have an example or erratic behavior?
